### PR TITLE
Add support for ArrayRef address attributes.

### PR DESCRIPTION
**Pull request by ssoriche**
Accept an ArrayRef as values for to, cc and bcc headers.

### CODE REVIEW

**Comment by pali** [comment]
Hi! I would suggest to not invent new stringification function (which is btw. incorrect), but rather use some that would appear underlying Email::MIME. This PR https://github.com/rjbs/Email-MIME/pull/38 brings module for correct parsing and generating of list of email addresses.

Anyway, what is the reason for adding another API how to pass list of email addresses into stuffer object? As you can already pass them normally (without need to construct array ref).

**Comment by ssoriche** [comment]
In our case, the list of email addresses is read from a configuration file as an ArrayRef. We experienced an issue with `send` silently failing (our bad) because of this. We've already dereferenced the ArrayRef in our code, but rather than someone else running into the same issue, I prepared this pull request.

**Comment by pali** [comment]
That is mistake of wrong usage. I'm not really sure if it is good idea to add another function API, just because somebody wrongly used current one...

But what is important, function `_stringify_addresses` is wrongly implemented. You cannot generate whole Cc or Bcc header just by adding char `,` between addresses. See PR https://github.com/rjbs/Email-MIME/pull/38 which should correctly compose/decompose addresses in address list headers.

I know that you just copied and current code (which joins addresses with `,`) into new function, but it is incorrect. Therefore I cannot approve or propose this patch for merge.

**Comment by rjbs** [comment]
To the extent that this fixed exactly one problem without fixing others, this is correct.  There is no reason to get into the sub-optimal use of `join` in reviewing this branch, unless it's to say "I made an issue about fixing that afterwards."

I think that rather than dereference, though, the code change should be to croak if an argument is not a string.  (Later, we can allow objects of the right type.)  @ssoriche If you're not stoked about updating this patch, that's cool, and I'll do it.  Let me know.

**Comment by pali** [comment]
> the code change should be to croak if an argument is not a string.

I agree. If input is totally incorrect (according to function API) then throwing error is correct behavior instead silently do something which does not have to make sense.

**Comment by pali** [comment]
I updated my PR https://github.com/rjbs/Email-MIME/pull/38 and now it allow to set array reference for header_str:
```
$email->header_str_set(To => [ 'user1@host.com', 'Name <user2@host.com>' ]);
```
@ssoriche this could fix your problem and also that incorrect join as whole construction of header would be done in Email::MIME. Email::Address::XS would take care of generating correct To header if is available.

**Comment by pali** [comment]
Hi! Starting with Email::MIME 1.943 it is possible to call:
```
$email->header_str_set(To => [ 'user1@host.com', 'Name <user2@host.com>' ]);
```
It is handled by a new module Email::MIME::Header::AddressList which is used by Email::MIME.

**Comment by ssoriche** [comment]
Sorry I have the change to `croak` locally, just haven't found the time to push it yet. I'll try to get it out later tonight.

**Comment by pali** [comment]
I'm going to prepare new PR which would fix that join problem and also address your needs (thanks to above Email::MIME support). So it would replace this PR.

**Comment by pali** [comment]
Here it is: https://github.com/rjbs/Email-Stuffer/pull/38 It supersedes this PR.

**Comment by ssoriche** [comment]
@rjbs I've updated my pull request, I'll rebase it down to one change if you'd like to continue with it.

**Comment by rjbs** [comment]
Thanks, I used this work as part of 2dfdee6, which rejects undef and unblessed ref values in the list of args to to/bcc/from/cc.

**Comment by rjbs** [comment]
What makes allowing an arrayref tempting is that arguments to `new` are lists of pairs, so the only way to pass a list of `to` args to new is an arrayref.  Will think on this as I head downstairs.

**Comment by rjbs** [comment]
Allowed by 07dc55c.

**Pull request closed without merging**
